"""
Event generated by the portfolio to order the given instrument. 

May only be necessary when live trading and there is a difference between the 
fill and the order events. 
"""

class OrderEvent(): 

    def __init__(self, ticker: str, quantity: int, price: int ):
        """
        :param ticker: tickery symbol
        :param quantity: quantity of instrument to purchase
        :param price: price of instument
        """
        self.__ticker = ticker
        self.__quantity = quantity
        self.__price = price 

    
    def getTicker():
        return self.__ticker

    def getQuantity(): 
        return self.__quantity

    def getPrice(): 
        return self.__price
        