#SignalEvent
"""
Event generated by the Strategy class that is sent to the Portfolio class. 

The portfolio will receive the event and process it with the help of the risk manager to 
incorporate the position into the portfolio. 
"""

class SignalEvent(): 

    # TODO --> varying time stamps depending on 
    def __init__(self, ticker: str, position: str, time_stamp: str):
        """
        :param ticker: the ticker symbol of trading signal
        :param position: long or short 
        "param time_stamp: ISO 8601 Format specification YYYY-MM-DD
        """
        self.__ticker = ticker
        self.__position = position
        self.__time_stamp = time_stamp

    def getTicker(): 
        return self.__ticker

    def getPosition(): 
        return self.__position

    def getTimeStamp(): 
        return self.__time_stamp